security:
  - name: demo
    type: basic_auth
    username: demo
    password: demo

pubsub_topic:
  - name: demo.1
    description: Demo topic 1

  - name: demo.2
    description: Demo topic 2

  - name: demo.3
    description: Demo topic 3

pubsub_permission:
  - security: demo
    pub:
      - demo.*
    sub:
      - demo.*

pubsub_subscription:
  - security: demo
    delivery_type: pull
    max_retry_time: 365d
    topic_list:
      - demo.1
      - demo.3
